tasks:
  - name: Install and Setup
    init: |
      pyenv install --skip-existing 3.8.12
      pip install -r requirements.txt
    command: python app.py
ports:
  - port: 5000
    onOpen: open-preview